### ISSUE TITLE
Pipe counter?

### ISSUE THREAD

**Issue by nm17** [dulex123/jj-farm#1]
How about adding an pipe counter?
Also gen counter.

**Comment by jodusan** [comment]
Hi! Fitness is similar to pipe number/time passed, so I think it would be a little bit of bloat-ish. What do you exactly mean by gen counter? Number of current generation?

**Comment by nm17** [comment]
> Number of current generation?  

Yes

**Comment by HIETE** [comment]
the video says current generation https://www.youtube.com/watch?v=L6bbFgjkqK0
but the code says columns passed. Where is the video version?

**Comment by jodusan** [comment]
Hey, as I've written somewhere in the comments on yt video, the latest version that can be seen on the video has been deleted by accident. So the one in the video is not available but those changes were mostly design-wise anyway.
